name: CI Backend

on:
  push:
    paths:
      - "./backend/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo $TEST_ACCOUNT >> serviceAccount.json
      shell: bash
      env:
        TEST_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT}}
        DB_SETTING: TEST
      working-directory: ./backend
    - name: Test with pytest
      run: |
        pytest --cov --cov-fail-under=85
      working-directory: ./backend
